import { Prisma } from '@prisma/client'

export const odProofSelectOptions = {
  id: true,
  studentId: true,
  registerNumber: true,
  studentName: true,
  year: true,
  section: true,
  semester: true,
  odRequestId: true,
  eventName: true,
  category: true,
  eventDate: true,
  venueCollege: true,
  durationFormat: true,
  latitude: true,
  longitude: true,
  geoAddress: true,
  geoTimestamp: true,
  certificateName: true,
  achievement: true,
  status: true,
  advisorRemarks: true,
  verifiedByName: true,
  verifiedAt: true,
  attendanceCredited: true,
  createdAt: true,
  updatedAt: true,
  // Specifically omit base64 fields:
  // geoPhotoUrl: false,
  // dailyProofs: false,
  // certificateUrl: false,
} satisfies Prisma.ODProofSelect
