export const FALLBACK_PROJECTS = [
  {
    id: 'proj-1',
    title: 'Autonomous Drone Navigation Using Deep Reinforcement Learning',
    description: 'Developed an end-to-end policy network utilizing Deep Q-Networks (DQN) and PPO to allow quadcopter drones to navigate dynamic indoor obstacles in real-time without GPS.',
    problemStatement: 'GPS-denied indoor environments present severe localization and obstacle collision challenges for autonomous micro-aerial vehicles.',
    proposedSolution: 'Integrated real-time LiDAR point-cloud clustering with continuous-action PPO policy for collision-free trajectory generation.',
    technologies: 'Python, PyTorch, ROS2, Gazebo, OpenAI Gym',
    domain: 'Computer Vision & Deep Learning',
    year: 2025,
    status: 'Approved & Active',
    guideName: 'Dr. S. Karthik (Professor)',
    guideEmail: 'karthik.ai@vsb.edu.in',
    teamMembers: 'K. Aishwarya (23AD001), S. Gokul (23AD002)',
    results: 'Achieved 96.4% collision avoidance success rate across 500 simulated obstacle-rich maze environments.',
    createdAt: new Date('2025-09-15'),
  },
  {
    id: 'proj-2',
    title: 'Multilingual Clinical Summarization & Diagnostic Assistant via Fine-Tuned LLaMA-3',
    description: 'Fine-tuned open-source 8B LLM on curated clinical SOAP notes and biomedical literature to generate concise, doctor-verified diagnostic summaries in English and Tamil.',
    problemStatement: 'Overburdened rural primary healthcare centers face severe documentation delays and communication barriers.',
    proposedSolution: 'Domain-adapted quantized LoRA fine-tuning for low-resource Indian languages with strict medical terminology guardrails.',
    technologies: 'Hugging Face, LoRA, QLoRA, FastAPI, Next.js, LangChain',
    domain: 'Natural Language Processing (NLP)',
    year: 2025,
    status: 'In Progress',
    guideName: 'Mrs. R. Priya (Asst. Prof)',
    guideEmail: 'priya.ai@vsb.edu.in',
    teamMembers: 'M. Harish (23AD003), V. Divya (23AD004)',
    results: 'ROUGE-L score of 0.68 and validated by 3 senior physicians with 91% factual accuracy.',
    createdAt: new Date('2025-10-02'),
  },
  {
    id: 'proj-3',
    title: 'Real-time Diabetic Retinopathy Grading using EfficientNet-B5 with Explainable AI',
    description: 'Fundus image classification pipeline with Grad-CAM and Integrated Gradients visualization to detect microaneurysms and hemorrhages in retinal scans.',
    problemStatement: 'Early screening of diabetic retinopathy requires expert ophthalmologists which are scarce in remote locations.',
    proposedSolution: 'Transfer learning on APTOS & EyePACS datasets with automated lesion heatmaps for clinician interpretability.',
    technologies: 'TensorFlow 2.x, OpenCV, Grad-CAM, React Native, Flask',
    domain: 'Healthcare & Predictive Analytics',
    year: 2025,
    status: 'Completed',
    guideName: 'Mr. S. Arun (Asst. Prof)',
    guideEmail: 'arun.ai@vsb.edu.in',
    teamMembers: 'P. Vignesh (23AD005), R. Sneha (23AD006)',
    results: 'Quadratic Weighted Kappa score of 0.923 and sensitivity of 94.8% on unseen clinical test sets.',
    createdAt: new Date('2025-08-20'),
  },
  {
    id: 'proj-4',
    title: 'Smart Agricultural IoT: Multi-Spectral Crop Disease & Yield Prediction',
    description: 'Edge-AI deployed on Raspberry Pi with multi-spectral sensors for soil moisture, nitrogen levels, and early crop blight detection.',
    problemStatement: 'Unpredictable weather and undetected fungal infections lead to 30% annual crop yield losses.',
    proposedSolution: 'Edge-optimized MobileNetV3 paired with LSTM temporal weather forecasting models.',
    technologies: 'Edge Impulse, TensorFlow Lite, Arduino, MQTT, Node-RED',
    domain: 'Graph Neural Networks & Smart Cities',
    year: 2025,
    status: 'Approved & Active',
    guideName: 'Dr. M. Sowmya (Associate Prof)',
    guideEmail: 'sowmya.ai@vsb.edu.in',
    teamMembers: 'N. Balaji (23AD007), T. Kaviya (23AD008)',
    results: 'Early detection of leaf blast disease 4 days prior to visual symptoms with 93% accuracy.',
    createdAt: new Date('2025-11-10'),
  },
]
