const { PrismaClient } = require('@prisma/client')
const bcrypt = require('bcryptjs')

const prisma = new PrismaClient()

const facultyList = [
  {
    name: 'Dr. S. K. Vijay Anand',
    designation: 'Professor & Head',
    qualification: 'Ph.D. (Information & Communication Engg), M.E. (CSE)',
    experience: 21,
    specialization: 'Artificial Intelligence, Deep Learning & Predictive Modeling',
    subjects: ['AI3401 - Artificial Intelligence', 'AD3501 - Deep Learning Technologies'],
    advisorBatch: '2022-2026',
    advisorYear: 4,
    advisorSem: 8,
    advisorSec: 'A',
  },
  {
    name: 'Dr. M. Soundararajan',
    designation: 'Professor',
    qualification: 'Ph.D. (Computer Science), M.Tech. (Data Analytics)',
    experience: 18,
    specialization: 'Big Data Analytics, Distributed Computing & Apache Spark',
    subjects: ['AD3502 - Big Data Analytics', 'CS3352 - Foundations of Data Science'],
    advisorBatch: '2022-2026',
    advisorYear: 4,
    advisorSem: 8,
    advisorSec: 'B',
  },
  {
    name: 'Dr. P. Kavitha',
    designation: 'Professor',
    qualification: 'Ph.D. (Machine Learning), M.E. (Software Engg)',
    experience: 17,
    specialization: 'Natural Language Processing & Large Language Models',
    subjects: ['AI3601 - Natural Language Processing', 'AD3491 - Fundamentals of Data Science'],
    advisorBatch: '2022-2026',
    advisorYear: 4,
    advisorSem: 8,
    advisorSec: 'C',
  },
  {
    name: 'Dr. R. Karthikeyan',
    designation: 'Associate Professor',
    qualification: 'Ph.D. (Computer Vision), M.E. (CSE)',
    experience: 15,
    specialization: 'Computer Vision, Image Processing & Autonomous Systems',
    subjects: ['AD3601 - Computer Vision & Applications', 'CS3491 - Artificial Intelligence and Machine Learning'],
    advisorBatch: '2023-2027',
    advisorYear: 3,
    advisorSem: 6,
    advisorSec: 'A',
  },
  {
    name: 'Dr. N. Geethanjali',
    designation: 'Associate Professor',
    qualification: 'Ph.D. (Neural Networks), M.Tech. (AI)',
    experience: 14,
    specialization: 'Neural Networks, Fuzzy Systems & Bio-Inspired AI',
    subjects: ['AI3501 - Neural Networks and Deep Learning', 'AD3301 - Data Exploration & Visualization'],
    advisorBatch: '2023-2027',
    advisorYear: 3,
    advisorSem: 6,
    advisorSec: 'B',
  },
  {
    name: 'Dr. G. Balakrishnan',
    designation: 'Associate Professor',
    qualification: 'Ph.D. (Cloud Computing), M.E. (CSE)',
    experience: 13,
    specialization: 'Cloud Infrastructure for AI, MLOps & Kubernetes',
    subjects: ['CS3591 - Computer Networks', 'AD3602 - Cloud Computing & DevOps for AI'],
    advisorBatch: '2023-2027',
    advisorYear: 3,
    advisorSem: 6,
    advisorSec: 'C',
  },
  {
    name: 'Dr. S. Meenakshi',
    designation: 'Associate Professor',
    qualification: 'Ph.D. (Data Science), M.Phil., M.Sc.',
    experience: 12,
    specialization: 'Applied Statistics, Probability Models & Stochastic AI',
    subjects: ['MA3354 - Discrete Mathematics', 'MA3151 - Matrices and Calculus'],
    advisorBatch: '2024-2028',
    advisorYear: 2,
    advisorSem: 4,
    advisorSec: 'A',
  },
  {
    name: 'Dr. V. Rajesh Kumar',
    designation: 'Assistant Professor (Sr. Grade)',
    qualification: 'Ph.D. (IoT & Edge AI), M.E. (Embedded Systems)',
    experience: 11,
    specialization: 'Edge Artificial Intelligence, TinyML & Embedded IoT',
    subjects: ['AD3401 - Embedded Systems for AI', 'EC3354 - Digital Principles and Computer Organization'],
    advisorBatch: '2024-2028',
    advisorYear: 2,
    advisorSem: 4,
    advisorSec: 'B',
  },
  {
    name: 'Mrs. A. Priyadharshini',
    designation: 'Assistant Professor (Sr. Grade)',
    qualification: 'M.E. (CSE), (Ph.D.)',
    experience: 10,
    specialization: 'Reinforcement Learning, Robotics & Multi-Agent Systems',
    subjects: ['AD3503 - Reinforcement Learning & Game Theory', 'CS3391 - Object Oriented Programming in Java'],
    advisorBatch: '2024-2028',
    advisorYear: 2,
    advisorSem: 4,
    advisorSec: 'C',
  },
  {
    name: 'Mr. K. Senthil Nathan',
    designation: 'Assistant Professor (Sr. Grade)',
    qualification: 'M.Tech. (Data Science), (Ph.D.)',
    experience: 10,
    specialization: 'Data Engineering, Real-Time Streaming & ETL Pipelines',
    subjects: ['AD3391 - Database Design and Management', 'AD3311 - Artificial Intelligence Laboratory'],
    advisorBatch: '2025-2029',
    advisorYear: 1,
    advisorSem: 2,
    advisorSec: 'A',
  },
  {
    name: 'Mrs. R. Malathi',
    designation: 'Assistant Professor',
    qualification: 'M.E. (Software Engineering)',
    experience: 9,
    specialization: 'Explainable AI, Model Interpretability & Algorithmic Ethics',
    subjects: ['AD3603 - Ethics in AI & Responsible AI', 'GE3151 - Problem Solving and Python Programming'],
    advisorBatch: '2025-2029',
    advisorYear: 1,
    advisorSem: 2,
    advisorSec: 'B',
  },
  {
    name: 'Mr. T. Dinesh Kumar',
    designation: 'Assistant Professor',
    qualification: 'M.E. (CSE)',
    experience: 8,
    specialization: 'Cybersecurity, Cryptography & Blockchain Analytics',
    subjects: ['CS3691 - Cryptography and Cybersecurity', 'CS3351 - Digital Principles and System Design'],
    advisorBatch: '2025-2029',
    advisorYear: 1,
    advisorSem: 2,
    advisorSec: 'C',
  },
  {
    name: 'Mrs. M. Jayanthi',
    designation: 'Assistant Professor',
    qualification: 'M.Tech. (Information Technology)',
    experience: 8,
    specialization: 'Semantic Web, Knowledge Graphs & Graph Neural Networks',
    subjects: ['AD3504 - Knowledge Engineering', 'AD3381 - Database Design & Management Laboratory'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. S. Aravindhan',
    designation: 'Assistant Professor',
    qualification: 'M.E. (CSE)',
    experience: 7,
    specialization: 'Generative AI, Diffusion Models & Transformer Architectures',
    subjects: ['AD3701 - Generative AI Applications', 'AD3411 - Data Science Laboratory'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. S. Nandhini Devi',
    designation: 'Assistant Professor',
    qualification: 'M.E. (Communication Systems)',
    experience: 7,
    specialization: 'Speech Processing, Audio Recognition & Acoustic Modeling',
    subjects: ['EC3492 - Digital Signal Processing for AI', 'AD3511 - Deep Learning Laboratory'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. P. Vigneshwaran',
    designation: 'Assistant Professor',
    qualification: 'M.Tech. (Artificial Intelligence & Data Science)',
    experience: 6,
    specialization: 'Full Stack AI Applications, Next.js & Python FastAPI',
    subjects: ['IT3501 - Full Stack Web Development for AI', 'GE3171 - Problem Solving & Python Programming Lab'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. K. Bhuvaneswari',
    designation: 'Assistant Professor',
    qualification: 'M.E. (Computer Science & Engineering)',
    experience: 6,
    specialization: 'Recommendation Systems & Predictive Customer Analytics',
    subjects: ['AD3604 - Recommender Systems', 'AD3611 - Computer Vision Laboratory'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. M. Anandha Kumar',
    designation: 'Assistant Professor',
    qualification: 'M.E. (CSE)',
    experience: 6,
    specialization: 'Automated Machine Learning (AutoML) & Hyperparameter Optimization',
    subjects: ['AD3702 - Automated Machine Learning Systems', 'AD3711 - Capstone Project Work Phase I'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. V. Divya Bharathi',
    designation: 'Assistant Professor',
    qualification: 'M.Tech. (Cyber Security)',
    experience: 5,
    specialization: 'Adversarial Machine Learning & Threat Detection',
    subjects: ['AD3703 - AI for Cyber Defense', 'CS3361 - Data Structures Laboratory in C/C++'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. G. Naveen Prasath',
    designation: 'Assistant Professor',
    qualification: 'M.E. (Software Engineering)',
    experience: 5,
    specialization: 'Quantum Machine Learning & Quantum Computing Algorithms',
    subjects: ['AD3801 - Quantum Computing Fundamentals', 'CS3461 - Operating Systems Laboratory'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Dr. C. Saravanan',
    designation: 'Associate Professor',
    qualification: 'Ph.D. (Information Technology), M.E.',
    experience: 13,
    specialization: 'High Performance Computing, GPU Acceleration & CUDA',
    subjects: ['CS3492 - Database Systems', 'AD3605 - Parallel and Distributed AI Computing'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. D. Ramya',
    designation: 'Assistant Professor',
    qualification: 'M.E. (CSE), (Ph.D.)',
    experience: 7,
    specialization: 'Medical Image Computing, Healthcare AI & Diagnostic Models',
    subjects: ['AD3704 - Healthcare Informatics & Medical AI', 'AD3412 - Machine Learning Laboratory'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. B. Suresh Babu',
    designation: 'Assistant Professor',
    qualification: 'M.Tech. (Computer Science)',
    experience: 8,
    specialization: 'Spatial Data Science, GIS Analytics & Satellite Vision',
    subjects: ['AD3705 - Geospatial Data Analytics', 'GE3271 - Engineering Practices Laboratory'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. E. Kanimozhi',
    designation: 'Assistant Professor',
    qualification: 'M.E. (CSE)',
    experience: 6,
    specialization: 'Time Series Forecasting, Financial Analytics & Algo-Trading',
    subjects: ['AD3606 - Financial Data Analytics', 'CS3391 - Object Oriented Programming'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. J. Mohanraj',
    designation: 'Assistant Professor',
    qualification: 'M.E. (Embedded Systems)',
    experience: 7,
    specialization: 'Autonomous Vehicles, Sensor Fusion & LiDAR Data Processing',
    subjects: ['AD3706 - Autonomous Driving AI Systems', 'AD3401 - Embedded Systems for AI'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. N. Suganya',
    designation: 'Assistant Professor',
    qualification: 'M.Tech. (Data Analytics)',
    experience: 5,
    specialization: 'Social Media Mining, Sentiment Analysis & Opinion Mining',
    subjects: ['AI3601 - Natural Language Processing', 'AD3301 - Data Exploration & Visualization'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. R. Praveen Kumar',
    designation: 'Assistant Professor',
    qualification: 'M.E. (CSE)',
    experience: 6,
    specialization: 'Federated Learning, Differential Privacy & Secure AI',
    subjects: ['AD3707 - Privacy Preserving Machine Learning', 'CS3591 - Computer Networks'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. T. Anitha',
    designation: 'Assistant Professor',
    qualification: 'M.E. (CSE)',
    experience: 8,
    specialization: 'Graph Analytics, Complex Networks & Social Network Analysis',
    subjects: ['CS3352 - Foundations of Data Science', 'AD3491 - Fundamentals of Data Science'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. K. Manikandan',
    designation: 'Assistant Professor',
    qualification: 'M.Tech. (Information Technology)',
    experience: 7,
    specialization: 'Compiler Optimization, Programming Paradigms & Algorithm Design',
    subjects: ['CS3451 - Design and Analysis of Algorithms', 'GE3151 - Problem Solving and Python Programming'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. S. Gayathri',
    designation: 'Assistant Professor',
    qualification: 'M.E. (Software Engineering)',
    experience: 6,
    specialization: 'Software Testing, Quality Assurance for Machine Learning Models',
    subjects: ['CS3501 - Software Engineering for Data Science', 'AD3511 - Deep Learning Laboratory'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Dr. M. Sivasankaran',
    designation: 'Associate Professor',
    qualification: 'Ph.D. (Machine Learning), M.E.',
    experience: 14,
    specialization: 'Bioinformatics, Genomics Data Science & Computational Biology',
    subjects: ['AD3802 - Bioinformatics Algorithms & Machine Learning', 'AI3401 - Artificial Intelligence'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. P. Revathi',
    designation: 'Assistant Professor',
    qualification: 'M.E. (CSE)',
    experience: 7,
    specialization: 'Information Retrieval, Vector Databases & Search Engines',
    subjects: ['AD3708 - Information Retrieval & Vector Search', 'AD3391 - Database Design and Management'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. V. Harish Kumar',
    designation: 'Assistant Professor',
    qualification: 'M.E. (Communication Systems)',
    experience: 5,
    specialization: '5G/6G Wireless AI, Cognitive Radio Networks & Smart Antennas',
    subjects: ['EC3354 - Digital Principles and Computer Organization', 'EC3492 - Digital Signal Processing for AI'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. K. Deepa',
    designation: 'Assistant Professor',
    qualification: 'M.Tech. (AI & Robotics)',
    experience: 6,
    specialization: 'Industrial Automation, PLC Programming & AI in Manufacturing',
    subjects: ['AD3803 - Industrial AI & Smart Manufacturing', 'AD3411 - Data Science Laboratory'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. S. Karthik Raj',
    designation: 'Assistant Professor',
    qualification: 'M.E. (CSE)',
    experience: 5,
    specialization: 'Metaverse Technologies, AR/VR Development & Spatial Computing',
    subjects: ['AD3709 - Augmented and Virtual Reality for AI', 'IT3501 - Full Stack Web Development for AI'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. R. Abirami',
    designation: 'Assistant Professor',
    qualification: 'M.E. (CSE)',
    experience: 6,
    specialization: 'Pattern Recognition, Document AI & OCR Systems',
    subjects: ['AD3601 - Computer Vision & Applications', 'CS3361 - Data Structures Laboratory'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. L. Gokulakrishnan',
    designation: 'Assistant Professor',
    qualification: 'M.Tech. (Data Science)',
    experience: 5,
    specialization: 'Behavioral Analytics, User Profiling & Clickstream Data Analysis',
    subjects: ['AD3502 - Big Data Analytics', 'AD3381 - Database Design & Management Laboratory'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. V. Sangeetha',
    designation: 'Assistant Professor',
    qualification: 'M.E. (Software Engineering)',
    experience: 7,
    specialization: 'Agile AI Development, Microservices Architecture & Containerization',
    subjects: ['CS3501 - Software Engineering for Data Science', 'AD3602 - Cloud Computing & DevOps for AI'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. N. Sasikumar',
    designation: 'Assistant Professor',
    qualification: 'M.E. (CSE)',
    experience: 8,
    specialization: 'Operating Systems Internals, Linux Kernel AI & System Programming',
    subjects: ['CS3461 - Operating Systems Laboratory', 'CS3351 - Digital Principles and System Design'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. B. Kaviyarasu',
    designation: 'Assistant Professor',
    qualification: 'M.E. (Information Technology)',
    experience: 6,
    specialization: 'E-Commerce Analytics, Supply Chain Optimization & AI Forecasting',
    subjects: ['AD3604 - Recommender Systems', 'AD3301 - Data Exploration & Visualization'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. T. Vigneshwaran',
    designation: 'Assistant Professor',
    qualification: 'M.Tech. (Artificial Intelligence)',
    experience: 5,
    specialization: 'Automated Dialogue Systems, Conversational AI & Rasa Framework',
    subjects: ['AI3601 - Natural Language Processing', 'AD3701 - Generative AI Applications'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. G. Pavithra',
    designation: 'Assistant Professor',
    qualification: 'M.E. (CSE)',
    experience: 7,
    specialization: 'Smart Grid Analytics, Energy AI & IoT Sensor Networks',
    subjects: ['AD3401 - Embedded Systems for AI', 'CS3591 - Computer Networks'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. M. Chelladurai',
    designation: 'Assistant Professor',
    qualification: 'M.E. (CSE)',
    experience: 9,
    specialization: 'Data Mining, Association Rule Learning & Frequent Itemset Mining',
    subjects: ['AD3491 - Fundamentals of Data Science', 'CS3352 - Foundations of Data Science'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. A. Swarnalatha',
    designation: 'Assistant Professor',
    qualification: 'M.Tech. (Data Analytics)',
    experience: 6,
    specialization: 'Fraud Detection Analytics, Risk Assessment & Anomaly Detection',
    subjects: ['AD3606 - Financial Data Analytics', 'AI3401 - Artificial Intelligence'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. R. Arunachalam',
    designation: 'Assistant Professor',
    qualification: 'M.E. (Computer Science)',
    experience: 8,
    specialization: 'Parallel Algorithms, OpenMP & High Speed Computing',
    subjects: ['AD3605 - Parallel and Distributed AI Computing', 'CS3451 - Design and Analysis of Algorithms'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. C. Menaka',
    designation: 'Assistant Professor',
    qualification: 'M.E. (CSE)',
    experience: 5,
    specialization: 'Intelligent Tutoring Systems, Educational Data Mining & E-Learning',
    subjects: ['AD3603 - Ethics in AI & Responsible AI', 'GE3151 - Problem Solving and Python Programming'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. S. Ramesh Kumar',
    designation: 'Assistant Professor',
    qualification: 'M.Tech. (Information Technology)',
    experience: 7,
    specialization: 'Database Indexing, Query Optimization & NoSQL Engines (MongoDB)',
    subjects: ['AD3391 - Database Design and Management', 'AD3381 - Database Design & Management Laboratory'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. K. Jayasree',
    designation: 'Assistant Professor',
    qualification: 'M.E. (Software Systems)',
    experience: 6,
    specialization: 'Continuous Integration / Continuous Deployment (CI/CD) for AI',
    subjects: ['AD3602 - Cloud Computing & DevOps for AI', 'IT3501 - Full Stack Web Development for AI'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mr. P. Subramanian',
    designation: 'Assistant Professor',
    qualification: 'M.E. (CSE)',
    experience: 8,
    specialization: 'Mathematical Modeling for AI, Linear Algebra & Optimization',
    subjects: ['MA3151 - Matrices and Calculus', 'MA3354 - Discrete Mathematics'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
  {
    name: 'Mrs. N. Sharmila',
    designation: 'Assistant Professor',
    qualification: 'M.Tech. (Artificial Intelligence & Data Science)',
    experience: 5,
    specialization: 'Multimodal AI, Audio-Visual Synthesis & Deepfake Detection',
    subjects: ['AD3501 - Deep Learning Technologies', 'AD3601 - Computer Vision & Applications'],
    advisorBatch: null,
    advisorYear: null,
    advisorSem: null,
    advisorSec: null,
  },
]

async function seed50Faculty() {
  console.log('🚀 Starting generation and enrollment of 50 AI & DS Faculty Members...')

  const defaultPassword = 'Faculty@123'
  const defaultPasswordHash = await bcrypt.hash(defaultPassword, 10)

  let totalInserted = 0

  for (let i = 0; i < facultyList.length; i++) {
    const fData = facultyList[i]
    const facultyIndex = i + 1
    const facultyId = `AIDS-FAC${String(facultyIndex).padStart(2, '0')}`
    const email = `${facultyId.toLowerCase()}@vsb.edu.in`
    const phone = `+91 94${String(40000000 + facultyIndex * 111111).slice(0, 8)}`
    const birthYear = 1975 + (i % 18) // Between 1975 and 1993
    const dob = new Date(`${birthYear}-0${(i % 9) + 1}-10`)

    try {
      const user = await prisma.user.upsert({
        where: { email },
        update: {
          name: fData.name,
          phone,
          role: 'faculty',
          status: 'active',
          passwordHash: defaultPasswordHash,
        },
        create: {
          email,
          name: fData.name,
          phone,
          role: 'faculty',
          status: 'active',
          passwordHash: defaultPasswordHash,
          mustChangePassword: true,
        },
      })

      await prisma.faculty.upsert({
        where: { facultyId },
        update: {
          userId: user.id,
          designation: fData.designation,
          qualification: fData.qualification,
          experience: fData.experience,
          specialization: fData.specialization,
          subjects: JSON.stringify(fData.subjects),
          subjectName: fData.subjects[0] || null,
          advisorBatch: fData.advisorBatch || null,
          advisorYear: fData.advisorYear || null,
          advisorSem: fData.advisorSem || null,
          advisorSec: fData.advisorSec || null,
          dateOfBirth: dob,
          facultyType: 'both',
        },
        create: {
          userId: user.id,
          facultyId,
          designation: fData.designation,
          qualification: fData.qualification,
          experience: fData.experience,
          specialization: fData.specialization,
          subjects: JSON.stringify(fData.subjects),
          subjectName: fData.subjects[0] || null,
          advisorBatch: fData.advisorBatch || null,
          advisorYear: fData.advisorYear || null,
          advisorSem: fData.advisorSem || null,
          advisorSec: fData.advisorSec || null,
          dateOfBirth: dob,
          facultyType: 'both',
        },
      })

      // If this faculty is assigned as a class advisor, ensure ClassAdvisor table is in sync
      if (fData.advisorYear && fData.advisorSec && fData.advisorSem) {
        await prisma.classAdvisor.upsert({
          where: {
            year_section_semester_academicYear: {
              year: fData.advisorYear,
              section: fData.advisorSec,
              semester: fData.advisorSem,
              academicYear: '2025-2026',
            },
          },
          update: {
            facultyId,
            facultyName: fData.name,
          },
          create: {
            facultyId,
            facultyName: fData.name,
            year: fData.advisorYear,
            section: fData.advisorSec,
            semester: fData.advisorSem,
            academicYear: '2025-2026',
          },
        })
      }

      totalInserted++
      process.stdout.write(`✅ [${facultyIndex}/50] Enrolled: ${facultyId} — ${fData.name} (${fData.designation})\n`)
    } catch (err) {
      console.error(`Error inserting faculty ${facultyId}:`, err.message)
    }
  }

  console.log(`\n🎉 Successfully enrolled all ${totalInserted} faculty members into the database!`)
  console.log('Default Faculty Login Password: Faculty@123')
}

seed50Faculty()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error('Fatal faculty seed error:', e)
    process.exit(1)
  })
